name: Action Base
description: Action Base Description
inputs:
  python-version:
    description: "python version"
    required: true
    default: "3.10"
  github-token:
    description: "GITHUB_TOKEN"
    required: true
    default: ""

# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:
    - name: Set up Python Version
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python --version
      shell: bash

    - name: Run Count
      uses: anviedd/github-actions-template/.github/actions/count@main

    - name: Run Lint
      uses: anviedd/github-actions-template/.github/actions/lint@main
      with:
        github-token: ${{ inputs.github-token }}

    - name: Run Metrics
      uses: anviedd/github-actions-template/.github/actions/metrics@main
      with:
        github-token: ${{ inputs.github-token }}

    - name: Run Security
      uses: anviedd/github-actions-template/.github/actions/security@main
      with:
        github-token: ${{ inputs.github-token }}

    - name: Run Type
      uses: anviedd/github-actions-template/.github/actions/type@main
      with:
        github-token: ${{ inputs.github-token }}
