name: Action Base
description: Action Base Description
inputs:
  python-version:
    description: "python version"
    required: false
    default: "3.10"
  github-token:
    description: "GITHUB_TOKEN"
    required: false
    default: ""
  app-line-count-dir:
    description: "app-line-count-dir path"
    required: false
    default: "./"

  max-absolute:
    description: "xenon's max-absolute"
    required: false
    default: "B"
  max-modules:
    description: "xenon's max-modules"
    required: false
    default: "A"
  max-average:
    description: "xenon's max-average"
    required: false
    default: "A"
  language:
    description: "analysis language"
    required: false
    default: "python"
  ccn:
    description: "lizard's ccn"
    required: false
    default: "10"

  bandit-yml-path:
    description: "bandit-yml file's path"
    required: false
    default: ""

  pyright-version:
    description: "pyright-version"
    required: false
    default: ""

  path:
    description: "lizard's path"
    required: false
    default: "."

# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:
    - name: Set up Python Version
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python --version
      shell: bash

    - name: Run Count
      uses: anviedd/github-actions-template/.github/actions/count@main
      with:
        app-line-count-dir: ${{ inputs.app-line-count-dir }}
        github-token: ${{ inputs.github-token }}

    - name: Run Lint
      uses: anviedd/github-actions-template/.github/actions/lint@main
      with:
        github-token: ${{ inputs.github-token }}

    - name: Run Metrics
      uses: anviedd/github-actions-template/.github/actions/metrics@main
      with:
        github-token: ${{ inputs.github-token }}
        max-absolute: ${{ inputs.max-absolute }}
        max-modules: ${{ inputs.max-modules }}
        max-average: ${{ inputs.max-average }}
        language: ${{ inputs.language }}
        ccn: ${{ inputs.ccn }}
        path: ${{ inputs.ccn }}

    - name: Run Security
      uses: anviedd/github-actions-template/.github/actions/security@main
      with:
        github-token: ${{ inputs.github-token }}
        bandit-yml-path: ${{ inputs.bandit-yml-path }}

    - name: Run Type
      uses: anviedd/github-actions-template/.github/actions/type@main
      with:
        github-token: ${{ inputs.github-token }}
        pyright-version: ${{ inputs.pyright-version }}
