name: Action Base
description: Action Base Description
inputs:
  python-version:
    description: "python version"
    required: true
    default: "3.11"

#   who-to-greet: # id of input
#     description: "Who to greet"
#     required: true
#     default: "World"
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:
    - name: Set up Python Version
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python --version
      shell: bash

    - name: Main Action
      run: |
        pwd
        echo ${{ github.action_path }}
        # ${{ github.action_path }}/goodbye.sh
      shell: bash

    - name: Run Count
      uses: anviedd/github-actions-template/.github/actions/count@main

    - name: Run Lint
      uses: anviedd/github-actions-template/.github/actions/lint@main

    - name: Run Metrics
      uses: anviedd/github-actions-template/.github/actions/metrics@main

    - name: Run Security
      uses: anviedd/github-actions-template/.github/actions/security@main

    - name: Run Type
      uses: anviedd/github-actions-template/.github/actions/type@main
