name: Analysis Linter
runs:
  using: "composite"
  steps:
    - name: Install dependencies Linter
      run: |
        python --version
        pip install flake8
      shell: bash

    - name: Lint
      run: |
        flake8 --statistics > ./.lint.log

    - name: Lint flake8-builtins
      run: |
        pip install flake8-builtins
        flake8 --statistics > ./.lint.log

    - name: Lint flake8-bugbear
      run: |
        pip install flake8-bugbear
        flake8 --statistics > ./.lint.log

    - name: Lint pep8-naming
      run: |
        pip install pep8-naming
        flake8 --statistics > ./.lint.log

    # - if: failure()
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     URL: ${{ github.event.pull_request.html_url }}
    #   run: |
    #     echo "" >> ./.lint.log
    #     echo "Lint" >> ./.lint.log
    #     echo "https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" >> ./.lint.log
    #     cat ./.lint.log

    #     gh pr comment --body-file ./.lint.log "${URL}"
