name: Analysis Count
inputs:
  github-token:
    description: "GITHUB_TOKEN"
    required: false
    default: ""
  app-line-count-dir:
    description: "app-line-count-dir path"
    required: true
    default: ""
  line-count-max:
    description: "line-count-max"
    required: false
    default: 600

runs:
  using: "composite"
  steps:
    - name: Install dependencies Linter
      run: |
        python --version
        pip install flake8
      shell: bash

    - name: App Line Count
      if: inputs.app-line-count-dir != ''
      run: |
        # LINE_COUNT=`find ./app -name "*.py" | xargs wc -l | awk '{ if ($1 >= 500) {print}}'`

        LINE_COUNT=`find ${{ inputs.app-line-count-dir }} -name "*.py" | xargs wc -l | awk '{ if ($1 >= ${{ inputs.line-count-max }}) {print}}'`
        echo $LINE_COUNT > line_count.log

        ls -la
        pwd

        ls -la .github/actions/count

        sh .github/actions/count/line_count.sh
      shell: bash

    - if: failure() && inputs.github-token != ''
      run: |
        URL=${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN=${{ inputs.github-token }}

        echo "\n" >> ./.count.log
        echo "# Line Count \n" >> ./.count.log
        echo "https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" >> ./.count.log

        cat line_count.log >> ./.count.log
        cat ./.count.log

        echo $URL
        echo $GITHUB_TOKEN

        gh pr comment --body-file ./.count.log "${URL}"
      shell: bash
