name: Analysis Count
inputs:
  app-line-count-dir:
    description: "app-line-count-dir path"
    required: true
    default: ""
  line-count-max:
    description: "line-count-max"
    required: false
    default: 650

runs:
  using: "composite"
  steps:
    - name: Install dependencies Linter
      run: |
        python --version
        pip install flake8
      shell: bash

    - name: App Line Count
      if: inputs.app-line-count-dir != ''
      run: |
        # LINE_COUNT=`find ./app -name "*.py" | xargs wc -l | awk '{ if ($1 >= 500) {print}}'`

        LINE_COUNT=`find ${{ inputs.app-line-count-dir }} -name "*.py" | xargs wc -l | awk '{ if ($1 >= ${{ inputs.line-count-max }}) {print}}'`
        echo $LINE_COUNT > line_count.log

        ls -la
        pwd

        # ls -la .github/actions/count

        # sh .github/actions/count/line_count.sh
      shell: bash

    - name: Output
      if: always()
      run: |
        if [ -f ./line_count.log ]; then
          cat ./line_count.log
        fi
      shell: bash
