name: Analysis metrics
inputs:
  github-token:
    description: "GITHUB_TOKEN"
    required: false
    default: ""
  max-absolute:
    description: "xenon's max-absolute"
    required: false
    default: "B"
  max-modules:
    description: "xenon's max-modules"
    required: false
    default: "A"
  max-average:
    description: "xenon's max-average"
    required: false
    default: "A"
  max-expression-complexity:
    required: false
    default: 8
  max-cognitive-complexity:
    required: false
    default: 7
  language:
    description: "analysis language"
    required: false
    default: "python"
  ccn:
    description: "lizard's ccn"
    required: false
    default: "10"
  path:
    description: "lizard's path"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Install dependencies Linter
      run: |
        echo ${{ inputs.github-token }}

        echo ${{ inputs.max-absolute }}
        echo ${{ inputs.max-modules }}
        echo ${{ inputs.max-average }}

        echo ${{ inputs.language }}
        echo ${{ inputs.ccn }}
        echo ${{ inputs.path }}

        python --version

        python -m pip install --upgrade pip
        pip install xenon
        pip install radon

        pip install flake8
        pip install flake8-cognitive-complexity
        pip install flake8-expression-complexity

        pip install lizard

      shell: bash

    - name: flake8-cognitive-complexity
      run: |
        echo "cognitive-complexity"
        flake8 --max-cognitive-complexity=${{ inputs.max-cognitive-complexity }} --statistics ${{ inputs.path }} > ./.metrics.log
      shell: bash

    - name: flake8-expression-complexity
      run: |
        echo "expression-complexity"
        flake8 --max-expression-complexity=${{ inputs.max-expression-complexity }} --statistics ${{ inputs.path }} > ./.metrics.log
      shell: bash

    - name: Lizard Runner
      run: |
        echo "Lizard Runner"
        ls -la && pwd

        echo ${{ inputs.language }}

        lizard --language ${{ inputs.language }} \
              --CCN ${{ inputs.ccn }} \
              --length 750 \
              --arguments 100 \
              --ignore_warnings 0 \
              --working_threads 4 \
              -T"nloc=1000000" ${{ inputs.path }} >> ./.metrics.log
        cat .metrics.log
      shell: bash

    - name: Xenon
      run: |
        xenon --max-absolute ${{ inputs.max-absolute }} \
              --max-modules ${{ inputs.max-modules }} \
              --max-average ${{ inputs.max-average }} ./ >> ./.metrics.log
      shell: bash

    - if: failure() && inputs.github-token != ''
      run: |
        URL=${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN=${{ inputs.github-token }}

        echo "\n" >> ./.metrics.log
        echo "# Metrics \n" >> ./.metrics.log
        echo "https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" >> ./.metrics.log

        echo $URL
        echo $GITHUB_TOKEN
        cat ./.metrics.log

        gh pr comment --body-file ./.metrics.log "${URL}"
      shell: bash
