name: Analysis metrics
inputs:
  python-version:
    description: "python version"
    required: true
    default: "3.10"
  max-absolute:
    description: "xenon's max-absolute"
    required: true
    default: "B"
  max-modules:
    description: "xenon's max-modules"
    required: true
    default: "A"
  max-average:
    description: "xenon's max-average"
    required: true
    default: "A"

runs:
  using: "composite"
  steps:
    - name: Install dependencies Linter
      run: |
        python --version

        python -m pip install --upgrade pip
        pip install xenon
        pip install radon

        pip install flake8
        pip install flake8-cognitive-complexity
        pip install flake8-expression-complexity

      shell: bash

    - name: flake8-cognitive-complexity
      run: |
        echo "cognitive-complexity"
        flake8 --max-cognitive-complexity=7 --statistics > ./.metrics.log
      shell: bash

    - name: flake8-expression-complexity
      run: |
        echo "expression-complexity"
        flake8 --max-expression-complexity=7 --statistics > ./.metrics.log
      shell: bash

    - name: Lizard Runner
      uses: Uno-Takashi/Lizard-Runner@v3
      with:
        language: "python"
        # path: "./"
        CCN: "10"
        output_file: "./.metrics.log"

    - name: Xenon
      run: |
        xenon --max-absolute ${{ inputs.max-absolute }} \
              --max-modules ${{ inputs.max-modules }} \
              --max-average ${{ inputs.max-average }} >> ./.metrics.log
      shell: bash
