name: Analysis Typing
runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        pip install pyright
        pip install mypy
        pip install refurb

      shell: bash

    - name: Run Pyright
      run: |
        pyright
      shell: bash

    - name: Run mypy
      run: |
        mypy ./ >> ./.type.log
      shell: bash

    - name: Run refurb
      run: |
        refurb ./ >> ./.type.log
      shell: bash
