name: Analysis Typing
inputs:
  pyright-version:
    description: "pyright-version"
    required: false
    default: ""
    # default: 1.1.308
  path:
    description: "path"
    required: false
    default: "."
    # default: 1.1.308

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        pip install mypy==1.6.1
        pip install refurb==1.20.0

        echo ${{ github.workspace }}

      shell: bash

    - name: Run mypy
      working-directory: ${{ inputs.path }}
      run: |
        echo ${{ inputs.path }}
        ls -la && pwd

        mypy ./ >> ${{ github.workspace }}/.type.log
      shell: bash

    - name: Run refurb
      working-directory: ${{ inputs.path }}
      run: |
        echo ${{ inputs.path }}
        ls -la && pwd

        refurb ./ >> ${{ github.workspace }}/.type.log
      shell: bash

    - name: Run pyright
      if: inputs.pyright-version == ''
      run: |
        pip install pyright
        ls -la && pwd
        pyright|grep "error" >> ${{ github.workspace }}/.type.log
      shell: bash

    - name: Run pyright (pyright-version)
      if: inputs.pyright-version != ''
      run: |
        pip install pyright==${{ inputs.pyright-version }}
        ls -la && pwd
        pyright|grep "error" >> ./.type.log
      shell: bash

    - name: Output
      if: always()
      run: |
        if [ -f ${{ github.workspace }}/.type.log ]; then
          cat ${{ github.workspace }}/.type.log
        fi
        if [ -f ./.type.log ]; then
          cat ./.type.log
        fi
      shell: bash
