name: Analysis Typing
inputs:
  github-token:
    description: "GITHUB_TOKEN"
    required: false
    default: ""
  pyright-version:
    description: "pyright-version"
    required: false
    default: ""
    # default: 1.1.308

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        # pip install pyright
        pip install mypy
        pip install refurb

      shell: bash

    - name: Run pyright
      if: inputs.pyright-version == ''
      uses: jakebailey/pyright-action@v1.5.1

    - name: Run pyright (pyright-version)
      if: inputs.pyright-version != ''
      uses: jakebailey/pyright-action@v1.5.1
      with:
        version: ${{ inputs.pyright-version }}

    - name: Run mypy
      run: |
        mypy ./ >> ./.type.log
      shell: bash

    - name: Run refurb
      run: |
        refurb ./ >> ./.type.log
      shell: bash

    - if: failure() && inputs.github-token != ''
      run: |
        URL=${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN=${{ inputs.github-token }}

        echo "\n" >> ./.type.log
        echo "# Type \n" >> ./.metrics.log
        echo "https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" >> ./.type.log

        echo $URL
        echo $GITHUB_TOKEN
        cat ./.type.log

        gh pr comment --body-file ./.type.log "${URL}"
      shell: bash
