name: Analysis Lint

runs:
  using: "composite"
  steps:
    - name: Install dependencies Linter
      run: |
        python --version
        pip install flake8
      shell: bash

    - name: Lint
      run: |
        echo "Lint"
        flake8 --statistics > ./.lint.log
      shell: bash

    - name: Lint flake8-builtins
      run: |
        echo "flake8-builtins"
        pip install flake8-builtins
        flake8 --statistics > ./.lint.log
      shell: bash

    - name: Lint flake8-bugbear
      run: |
        echo "flake8-bugbear"
        pip install flake8-bugbear
        flake8 --statistics > ./.lint.log
      shell: bash

    - name: Lint pep8-naming
      run: |
        echo "pep8-naming"
        pip install pep8-naming
        flake8 --statistics > ./.lint.log
      shell: bash
