name: Analysis Lint
inputs:
  github-token:
    description: "GITHUB_TOKEN"
    required: true
    default: ""

runs:
  using: "composite"
  steps:
    - name: Install dependencies Linter
      run: |
        python --version
        pip install flake8
      shell: bash

    - name: Lint
      run: |
        flake8 --statistics > ./.lint.log
      shell: bash

    - name: Lint flake8-builtins
      run: |
        pip install flake8-builtins
        flake8 --statistics > ./.lint.log
      shell: bash

    - name: Lint flake8-bugbear
      run: |
        pip install flake8-bugbear
        flake8 --statistics > ./.lint.log
      shell: bash

    - name: Lint pep8-naming
      run: |
        pip install pep8-naming
        flake8 --statistics > ./.lint.log
      shell: bash

    - if: failure() && inputs.github-token != ''
      run: |
        URL=${{ github.event.pull_request.html_url }}
        GITHUB_TOKEN=${{ inputs.github-token }}

        # echo "" >> ./.lint.log
        # echo "Lint" >> ./.lint.log
        # echo "https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" >> ./.lint.log

        echo $URL
        echo $GITHUB_TOKEN
        cat ./.lint.log

        # gh pr comment --body-file ./.lint.log "${URL}"
      shell: bash
