name: Analysis Codes
on:
  pull_request:
    branches-ignore:
      - staging
      - main
      - master
    types: [opened, synchronize]

  push:
    branches:
      - develop
      - staging
      - main

  workflow_dispatch:
    inputs:
      python-version:
        description: "python version"
        required: true
        default: "3.10"

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python Version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - run: |
          pwd && ls -la
          echo ${{ inputs.python-version }}
        shell: bash

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python --version
        shell: bash

      - name: Run Count
        uses: anviedd/github-actions-template/.github/actions/count@main

      - name: Run Lint
        uses: anviedd/github-actions-template/.github/actions/lint@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Metrics
        uses: anviedd/github-actions-template/.github/actions/metrics@main
        # with:
        #   github-token: ${{ secrets.GITHUB_TOKEN }}
        #   max-absolute: "B"
        #   max-modules: "A"
        #   max-average: "A"

      - name: Run Security
        uses: anviedd/github-actions-template/.github/actions/security@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Type
        uses: anviedd/github-actions-template/.github/actions/type@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
