name: Analysis Codes
on:
  pull_request:
    branches-ignore:
      - staging
      - main
      - master
    types: [opened, synchronize]

  push:
    branches:
      - develop
      - staging
      - main

  workflow_dispatch:
    inputs:
      text:
        type: string
        required: true
        description: "Text data"

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: |
          pwd && ls -la
        shell: bash

      - name: Run Analysis
        uses: ./.github/actions
