name: Analysis Codes
on:
  pull_request:
    branches-ignore:
      - staging
      - main
      - master
    types: [opened, synchronize]

  push:
    branches:
      - develop
      - staging
      - main

  workflow_dispatch:
    inputs:
      python-version:
        description: "python version"
        required: false
        default: "3.10"

      app-line-count-dir:
        description: "app-line-count-dir path"
        required: false
        default: "./"

      max-absolute:
        description: "xenon's max-absolute"
        required: false
        default: "B"
      max-modules:
        description: "xenon's max-modules"
        required: false
        default: "A"
      max-average:
        description: "xenon's max-average"
        required: false
        default: "A"
      language:
        description: "analysis language"
        required: false
        default: "python"
      ccn:
        description: "lizard's ccn"
        required: false
        default: "10"

      bandit-yml-path:
        description: "bandit-yml file's path"
        required: false
        default: ""

      pyright-version:
        description: "pyright-version"
        required: false
        default: ""

      path:
        description: "lizard's path"
        required: false
        default: "."

jobs:
  analysis:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python Version
        uses: actions/setup-python@v4
        # with:
        #   python-version: ${{ inputs.python-version }}

      - run: |
          pwd && ls -la
          echo ${{ inputs.python-version }}
        shell: bash

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python --version
        shell: bash

      - name: Run Count
        uses: anviedd/github-actions-template/.github/actions/count@main
        with:
          # app-line-count-dir: ${{ inputs.app-line-count-dir }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Lint
        uses: anviedd/github-actions-template/.github/actions/lint@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Metrics
        uses: anviedd/github-actions-template/.github/actions/metrics@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          max-absolute: "A"
          max-modules: "A"
          max-average: "A"
          language: "python"
          ccn: "10"
          path: "."

      - name: Run Security
        uses: anviedd/github-actions-template/.github/actions/security@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          bandit-yml-path: ${{ inputs.bandit-yml-path }}

      - name: Run Type
        uses: anviedd/github-actions-template/.github/actions/type@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ inputs.path }}
