name: Analysis Codes
on:
  pull_request:
    branches-ignore:
      - staging
      - main
      - master
    types: [opened, synchronize]

  push:
    branches:
      - develop
      - staging
      - main

  workflow_dispatch:
    inputs:
      python-version:
        description: "python version"
        required: true
        default: "3.11"

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python Version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - run: |
          pwd && ls -la
        shell: bash

      - name: Run Analysis
        uses: ./.github/actions

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python --version
        shell: bash

      - name: Main Action
        run: |
          pwd
          echo ${{ github.action_path }}
          # ${{ github.action_path }}/goodbye.sh
        shell: bash

      - name: Run Count
        uses: ./.github/actions/count@main

      - name: Run Lint
        uses: ./.github/actions/lint@main

      - name: Run Metrics
        uses: ./.github/actions/metrics@main

      - name: Run Security
        uses: ./.github/actions/security@main

      - name: Run Type
        uses: ./.github/actions/type@main
