name: Analysis Codes
on:
  pull_request:
    branches-ignore:
      - staging
      - main
      - master
    types: [opened, synchronize]

  push:
    branches:
      - develop
      - staging
      - main

  workflow_dispatch:
    inputs:

jobs:
  count:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Action Main Test
        uses: ./action.yml
        # with:
        #   who-to-greet: "Mona the Octocat"

      # - name: App Line Count
      #   shell: bash
      #   run: |
      #     # LINE_COUNT=`find ./app -name "*.py" | xargs wc -l | awk '{ if ($1 >= 500) {print}}'`
      #     # echo $LINE_COUNT > line_count.log
      #     ls -la
      #     pwd
      #     # sh .github/workflows/line_count.sh
